sudo: false
language: node_js
before_install:
- rvm install 2.3.1
- npm install -g grunt-cli
- export PATH=$HOME/.local/bin:${PATH}
install:
- npm install
script:
- if [[ $TRAVIS_BRANCH == "master" ]]; then grunt build && grunt deploy --bucket=storage.dasmicrobot.com;
  else grunt build; fi;
env:
  global:
  - secure: FafeEq5n1DMbr1QMAV5ss8iR26TvMqjAevApmFZk9W0FYf39nSPNq9ikV1gGaWFZlw0a2kPyBnHkskp9ZRBUNmipujFiPMQCwKA9Hhp5gF0IZTvelgFJ9H1/WnGslvYeM7SO7+Ohzqj74ami1uPkixG36q11Q0sgLuj2iNrkqNkZbk5ZVcYBz/sWGyMT4/1fCrCFWUADuVEZGURi8/TfB3b3qNyxKR/63b+UcG5ePdhPHGwzwiNAWmHucTGzQd4b0jHhWxm111lZFtBrDyhU6TERAVfjlkjxxZRsOlGchYG+yf1pB3duUCJoOOItPgYhAXkXDI0bhpdXwTSmOeJIk/UlFyS/pJSk6ec/2WqJtDgv4Pm90223D/noCEkhttRndZ+2+M5NMJuZIDbWFcDeXIyaW5Su/TwH3pFiG9HRDhbei71VJOQPBYtCPniQR6Nd7/FMQ1H5ED/BsvplUMeXTgeE0rQeYivST4vdvjwYcPpSu415788ccSOxbsgosBD2I+lh6tDBh+uCxBcw5zaFD1aMlAL34Cna2ChRIJynOqzLReCAP9Dy5IGaivHCFC4FHB7Jo6rB2n6JMENJm6n1Px9GXrqFIvj7KICLkmBbmfCNm5vgXNWDhGJdfIdA3El68obDJq5GaZyV2U6rqwYlpuGe2lzSTcVYr9GfAWemt4c=
  - secure: A8NX+lUtttaoeiRJANwRoLqwwhkFnzNJV1JjfF1oTSp0/C5l2ls4MiEYK7GGo2MiKxUOXgdspSnUHS69LWBQtRdlxb1G9Tf0d3Vj1ok1MH7y3LWwor4pxQAGSnJoI5SHu4cQsYJXCzCUgEYY2B2QjnTrPJWRC39h/9MiUe427irtAQfzG0exk+SsscWJKjdaP7ia8NF0xzp66h8jW+gi/wOh1h+ZvR+hCxj5W5fAiwdy+6y9e+jb4pnYgKGulu7SXo1z6tfssP+Ywlwnhx1qiLa9hZTo8rlx8vVL/7/6pRZ2VaqkhkSF04lhf8Czsq/EHtNUQK9KgiMUUvotis9WBHLPNbBHfVzXzjsqRg1cnqVVnaIQC0N2vLx8FsL6mbpv1RkPzmDTHm4Xvfg62YoYTIArWxdWUnOdoIykrO9XsID1zPvB1DgNeNLosgpIcQiC5m+T1gBt+ASSMc06x7Jg973fvtW1wv/aUo9BTU6XTBpo1lyfIqIRAjAAdWsNM0ABJUEH6FXkTgXDW4HdqdErCuHQOM4bpdgJtE2zzvZDDHokKKefLN/UL6S6b+vu7fkq65ExJAohdgtdvLF18YanmjgIyaO7XD5E45c4gvU7kVFLl9WQhe3f/km9G2NPnpw8I8+kgYQT4Q5ZgxNo60ichK8fhbzvFS4C+CXHuoK6DYE=
